language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
install:
- pip install ".[test]" .
script: python -m coverage run -m pytest tests
after_success:
- python -m codecov
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
