---
- hosts: example.int.dvt.at

# Note: we generate two private keys: privkey-account.pem is used by the acme_certificate module to talk to the acme server, privkey.pem is the private key of the tls certificate.

  tasks:
  - name: Generate a private key for the acme client
    openssl_privatekey:
      path: /tmp/privkey-account.pem
      size: 3072

  - name: Generate a private key for the TLS cert
    openssl_privatekey:
      path: /etc/pki/tls/private/example.int.dvt.at.key
      size: 3072

  - name: Generate a CSR. ACME_CERTIFICATE expects the correct CN and SANs present!
    openssl_csr:
      path: /etc/pki/tls/private/example.int.dvt.at.csr
      privatekey_path: /tmp/privkey-account.pem
      # email_address: netz@dvt.at  # muss nicht angegeben werden; falls angegeben, wird an EJBCA weitergereicht
      common_name: example.int.dvt.at
      subject_alt_name: 'DNS:www.example.int.dvt.at,DNS:example.int.dvt.at'

  - name: "get challenges"
    acme_certificate:
      account_key_src: /tmp/privkey-account.pem
      csr: /etc/pki/tls/private/example.int.dvt.at.csr
      dest: /etc/pki/tls/certs/example.int.dvt.at.crt
      acme_directory: https://acme.intra.tirol.gv.at:8443/directory
      acme_version: 2
    register: acme_challenge

  - file: path=/var/www/.well-known/acme-challenge state=directory
  - copy:
      #dest: /var/www/{{ item.key }}/{{ item.value['http-01']['resource'] }}
      dest: "/var/www/{{ item.value['http-01']['resource'] }}"
      content: "{{ item.value['http-01']['resource_value'] }}"
    loop: "{{ acme_challenge.challenge_data |default({})| dict2items }}"
    when: acme_challenge is changed

  - name: get certificate
    acme_certificate:
      account_key_src: /tmp/privkey-account.pem
      csr: /etc/pki/tls/private/example.int.dvt.at.csr
      dest: /etc/pki/tls/certs/example.int.dvt.at.crt
      acme_directory: https://acme.intra.tirol.gv.at:8443/directory
      acme_version: 2
      data: "{{ acme_challenge }}"
    when: acme_challenge is changed
